### ISSUE TITLE
Website - Cannot see edits on local branch on website

### ISSUE THREAD

**Issue by Sil-Ethan** [cadalyjr/pchem_intro#26]
![image](https://user-images.githubusercontent.com/106181004/179060068-7622c6bb-4660-4263-a369-62bdf1d9a9c6.png)
Here, I have a summation section that is within the non-main branch called "math-summation-ethan." However, I cannot visualize these changes on the actual website: 
![image](https://user-images.githubusercontent.com/106181004/179060333-d650c14c-5ceb-4671-a495-217f5df8b34c.png)

Do I have to make a pull request every time to make sure it shows up properly on the website?

**Comment by cadalyjr** [comment]
only the branch gh-pages is deployed as the actual website!
